/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package hu.webtown.liferay.tvtracker.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import hu.webtown.liferay.tvtracker.model.TvShow;
import hu.webtown.liferay.tvtracker.model.TvShowModel;
import hu.webtown.liferay.tvtracker.model.TvShowSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the TvShow service. Represents a row in the &quot;TvT_TvShow&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link hu.webtown.liferay.tvtracker.model.TvShowModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TvShowImpl}.
 * </p>
 *
 * @author czeni
 * @see TvShowImpl
 * @see hu.webtown.liferay.tvtracker.model.TvShow
 * @see hu.webtown.liferay.tvtracker.model.TvShowModel
 * @generated
 */
@JSON(strict = true)
public class TvShowModelImpl extends BaseModelImpl<TvShow>
	implements TvShowModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a tv show model instance should use the {@link hu.webtown.liferay.tvtracker.model.TvShow} interface instead.
	 */
	public static final String TABLE_NAME = "TvT_TvShow";
	public static final Object[][] TABLE_COLUMNS = {
			{ "tvShowId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "title", Types.VARCHAR },
			{ "premierDate", Types.TIMESTAMP },
			{ "description", Types.VARCHAR },
			{ "imageUrl", Types.VARCHAR },
			{ "imageUuid", Types.VARCHAR },
			{ "imageTitle", Types.VARCHAR },
			{ "imageVersion", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table TvT_TvShow (tvShowId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,title VARCHAR(75) null,premierDate DATE null,description VARCHAR(500) null,imageUrl VARCHAR(500) null,imageUuid VARCHAR(75) null,imageTitle VARCHAR(75) null,imageVersion VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table TvT_TvShow";
	public static final String ORDER_BY_JPQL = " ORDER BY tvShow.title ASC";
	public static final String ORDER_BY_SQL = " ORDER BY TvT_TvShow.title ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.hu.webtown.liferay.tvtracker.model.TvShow"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.hu.webtown.liferay.tvtracker.model.TvShow"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.hu.webtown.liferay.tvtracker.model.TvShow"),
			true);
	public static long GROUPID_COLUMN_BITMASK = 1L;
	public static long TVSHOWID_COLUMN_BITMASK = 2L;
	public static long TITLE_COLUMN_BITMASK = 4L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static TvShow toModel(TvShowSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		TvShow model = new TvShowImpl();

		model.setTvShowId(soapModel.getTvShowId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setTitle(soapModel.getTitle());
		model.setPremierDate(soapModel.getPremierDate());
		model.setDescription(soapModel.getDescription());
		model.setImageUrl(soapModel.getImageUrl());
		model.setImageUuid(soapModel.getImageUuid());
		model.setImageTitle(soapModel.getImageTitle());
		model.setImageVersion(soapModel.getImageVersion());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<TvShow> toModels(TvShowSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<TvShow> models = new ArrayList<TvShow>(soapModels.length);

		for (TvShowSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.hu.webtown.liferay.tvtracker.model.TvShow"));

	public TvShowModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _tvShowId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setTvShowId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _tvShowId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return TvShow.class;
	}

	@Override
	public String getModelClassName() {
		return TvShow.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("tvShowId", getTvShowId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("title", getTitle());
		attributes.put("premierDate", getPremierDate());
		attributes.put("description", getDescription());
		attributes.put("imageUrl", getImageUrl());
		attributes.put("imageUuid", getImageUuid());
		attributes.put("imageTitle", getImageTitle());
		attributes.put("imageVersion", getImageVersion());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long tvShowId = (Long)attributes.get("tvShowId");

		if (tvShowId != null) {
			setTvShowId(tvShowId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String title = (String)attributes.get("title");

		if (title != null) {
			setTitle(title);
		}

		Date premierDate = (Date)attributes.get("premierDate");

		if (premierDate != null) {
			setPremierDate(premierDate);
		}

		String description = (String)attributes.get("description");

		if (description != null) {
			setDescription(description);
		}

		String imageUrl = (String)attributes.get("imageUrl");

		if (imageUrl != null) {
			setImageUrl(imageUrl);
		}

		String imageUuid = (String)attributes.get("imageUuid");

		if (imageUuid != null) {
			setImageUuid(imageUuid);
		}

		String imageTitle = (String)attributes.get("imageTitle");

		if (imageTitle != null) {
			setImageTitle(imageTitle);
		}

		String imageVersion = (String)attributes.get("imageVersion");

		if (imageVersion != null) {
			setImageVersion(imageVersion);
		}
	}

	@JSON
	@Override
	public long getTvShowId() {
		return _tvShowId;
	}

	@Override
	public void setTvShowId(long tvShowId) {
		_columnBitmask |= TVSHOWID_COLUMN_BITMASK;

		if (!_setOriginalTvShowId) {
			_setOriginalTvShowId = true;

			_originalTvShowId = _tvShowId;
		}

		_tvShowId = tvShowId;
	}

	public long getOriginalTvShowId() {
		return _originalTvShowId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getTitle() {
		if (_title == null) {
			return StringPool.BLANK;
		}
		else {
			return _title;
		}
	}

	@Override
	public void setTitle(String title) {
		_columnBitmask = -1L;

		_title = title;
	}

	@JSON
	@Override
	public Date getPremierDate() {
		return _premierDate;
	}

	@Override
	public void setPremierDate(Date premierDate) {
		_premierDate = premierDate;
	}

	@JSON
	@Override
	public String getDescription() {
		if (_description == null) {
			return StringPool.BLANK;
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		_description = description;
	}

	@JSON
	@Override
	public String getImageUrl() {
		if (_imageUrl == null) {
			return StringPool.BLANK;
		}
		else {
			return _imageUrl;
		}
	}

	@Override
	public void setImageUrl(String imageUrl) {
		_imageUrl = imageUrl;
	}

	@JSON
	@Override
	public String getImageUuid() {
		if (_imageUuid == null) {
			return StringPool.BLANK;
		}
		else {
			return _imageUuid;
		}
	}

	@Override
	public void setImageUuid(String imageUuid) {
		_imageUuid = imageUuid;
	}

	@JSON
	@Override
	public String getImageTitle() {
		if (_imageTitle == null) {
			return StringPool.BLANK;
		}
		else {
			return _imageTitle;
		}
	}

	@Override
	public void setImageTitle(String imageTitle) {
		_imageTitle = imageTitle;
	}

	@JSON
	@Override
	public String getImageVersion() {
		if (_imageVersion == null) {
			return StringPool.BLANK;
		}
		else {
			return _imageVersion;
		}
	}

	@Override
	public void setImageVersion(String imageVersion) {
		_imageVersion = imageVersion;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			TvShow.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public TvShow toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (TvShow)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TvShowImpl tvShowImpl = new TvShowImpl();

		tvShowImpl.setTvShowId(getTvShowId());
		tvShowImpl.setGroupId(getGroupId());
		tvShowImpl.setCompanyId(getCompanyId());
		tvShowImpl.setUserId(getUserId());
		tvShowImpl.setUserName(getUserName());
		tvShowImpl.setCreateDate(getCreateDate());
		tvShowImpl.setModifiedDate(getModifiedDate());
		tvShowImpl.setTitle(getTitle());
		tvShowImpl.setPremierDate(getPremierDate());
		tvShowImpl.setDescription(getDescription());
		tvShowImpl.setImageUrl(getImageUrl());
		tvShowImpl.setImageUuid(getImageUuid());
		tvShowImpl.setImageTitle(getImageTitle());
		tvShowImpl.setImageVersion(getImageVersion());

		tvShowImpl.resetOriginalValues();

		return tvShowImpl;
	}

	@Override
	public int compareTo(TvShow tvShow) {
		int value = 0;

		value = getTitle().compareTo(tvShow.getTitle());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof TvShow)) {
			return false;
		}

		TvShow tvShow = (TvShow)obj;

		long primaryKey = tvShow.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		TvShowModelImpl tvShowModelImpl = this;

		tvShowModelImpl._originalTvShowId = tvShowModelImpl._tvShowId;

		tvShowModelImpl._setOriginalTvShowId = false;

		tvShowModelImpl._originalGroupId = tvShowModelImpl._groupId;

		tvShowModelImpl._setOriginalGroupId = false;

		tvShowModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<TvShow> toCacheModel() {
		TvShowCacheModel tvShowCacheModel = new TvShowCacheModel();

		tvShowCacheModel.tvShowId = getTvShowId();

		tvShowCacheModel.groupId = getGroupId();

		tvShowCacheModel.companyId = getCompanyId();

		tvShowCacheModel.userId = getUserId();

		tvShowCacheModel.userName = getUserName();

		String userName = tvShowCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			tvShowCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			tvShowCacheModel.createDate = createDate.getTime();
		}
		else {
			tvShowCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			tvShowCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			tvShowCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		tvShowCacheModel.title = getTitle();

		String title = tvShowCacheModel.title;

		if ((title != null) && (title.length() == 0)) {
			tvShowCacheModel.title = null;
		}

		Date premierDate = getPremierDate();

		if (premierDate != null) {
			tvShowCacheModel.premierDate = premierDate.getTime();
		}
		else {
			tvShowCacheModel.premierDate = Long.MIN_VALUE;
		}

		tvShowCacheModel.description = getDescription();

		String description = tvShowCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			tvShowCacheModel.description = null;
		}

		tvShowCacheModel.imageUrl = getImageUrl();

		String imageUrl = tvShowCacheModel.imageUrl;

		if ((imageUrl != null) && (imageUrl.length() == 0)) {
			tvShowCacheModel.imageUrl = null;
		}

		tvShowCacheModel.imageUuid = getImageUuid();

		String imageUuid = tvShowCacheModel.imageUuid;

		if ((imageUuid != null) && (imageUuid.length() == 0)) {
			tvShowCacheModel.imageUuid = null;
		}

		tvShowCacheModel.imageTitle = getImageTitle();

		String imageTitle = tvShowCacheModel.imageTitle;

		if ((imageTitle != null) && (imageTitle.length() == 0)) {
			tvShowCacheModel.imageTitle = null;
		}

		tvShowCacheModel.imageVersion = getImageVersion();

		String imageVersion = tvShowCacheModel.imageVersion;

		if ((imageVersion != null) && (imageVersion.length() == 0)) {
			tvShowCacheModel.imageVersion = null;
		}

		return tvShowCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(29);

		sb.append("{tvShowId=");
		sb.append(getTvShowId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", title=");
		sb.append(getTitle());
		sb.append(", premierDate=");
		sb.append(getPremierDate());
		sb.append(", description=");
		sb.append(getDescription());
		sb.append(", imageUrl=");
		sb.append(getImageUrl());
		sb.append(", imageUuid=");
		sb.append(getImageUuid());
		sb.append(", imageTitle=");
		sb.append(getImageTitle());
		sb.append(", imageVersion=");
		sb.append(getImageVersion());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(46);

		sb.append("<model><model-name>");
		sb.append("hu.webtown.liferay.tvtracker.model.TvShow");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>tvShowId</column-name><column-value><![CDATA[");
		sb.append(getTvShowId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>title</column-name><column-value><![CDATA[");
		sb.append(getTitle());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>premierDate</column-name><column-value><![CDATA[");
		sb.append(getPremierDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>description</column-name><column-value><![CDATA[");
		sb.append(getDescription());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>imageUrl</column-name><column-value><![CDATA[");
		sb.append(getImageUrl());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>imageUuid</column-name><column-value><![CDATA[");
		sb.append(getImageUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>imageTitle</column-name><column-value><![CDATA[");
		sb.append(getImageTitle());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>imageVersion</column-name><column-value><![CDATA[");
		sb.append(getImageVersion());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = TvShow.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] { TvShow.class };
	private long _tvShowId;
	private long _originalTvShowId;
	private boolean _setOriginalTvShowId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _userId;
	private String _userUuid;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private String _title;
	private Date _premierDate;
	private String _description;
	private String _imageUrl;
	private String _imageUuid;
	private String _imageTitle;
	private String _imageVersion;
	private long _columnBitmask;
	private TvShow _escapedModel;
}